---
title: "5-differential_abundance_time.Rmd"
author: "Antton Alberdi"
date: "2023-12-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r libraries, warning=FALSE, comments="", message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(ANCOMBC))
```

## Load data

```{r load_data}
load("data/data.Rdata")
```

## Prepare input

Only faecal samples.

```{r prepare_input, warning=FALSE, comments="", message=FALSE}
phylo_samples <- sample_metadata %>% 
                    filter(type == "faeces") %>% #filter only faecal samples
                    column_to_rownames("sample") %>% 
                    mutate(treatment = factor(treatment, levels = c("TJ1","TJ2"))) %>% 
                    mutate(day = factor(day, levels = c("0","7","14","21","28"))) %>% 
                    mutate(animal = factor(animal)) %>% 
                    sample_data() #convert to phyloseq sample_data object

phylo_counts <- genome_counts %>% 
                    column_to_rownames("genome") %>% 
                    mutate_all(~ replace(., . == 0, 0.00001)) %>% #add pseudo counts 
                    select(all_of(row.names(phylo_samples))) %>% #filter only faecal samples
                    otu_table(., taxa_are_rows = TRUE) #convert to phyloseq otu_table object

phylo_taxonomy <- genome_metadata %>% 
                    mutate(genome2=genome) %>% #create a pseudo genome name column
                    column_to_rownames("genome2") %>% 
                    select(domain,phylum,class,order,family,genus,species,genome) %>% #add an additional taxonomic level to ensure genome-level analysis (as no all genomes have species-level taxonomic assignments. Otherwise, ANCOMBC2 aggregates analyses per species)
                    as.matrix() %>% 
                    tax_table() #convert to phyloseq tax_table object

#Generate phyloseq object required to input ANCOMBC
genome_data <- phyloseq(phylo_counts, phylo_taxonomy, phylo_samples)
```



```{r ancombc2, warning=FALSE, comments="", message=FALSE}

set.seed(1234) #set seed for reproducibility
ancom_output = ancombc2(data = genome_data, 
                  assay_name = "counts", 
                  tax_level = NULL, #change to agglomerate analysis to a higher taxonomic range
                  fix_formula = "day", #fixed variable(s)
                  rand_formula = "1|animal",
                  p_adj_method = "holm", 
                  pseudo_sens = TRUE,
                  prv_cut = 0.10, 
                  lib_cut = 1000, 
                  s0_perc = 0.05,
                  group = NULL, 
                  struc_zero = FALSE, 
                  neg_lb = FALSE,
                  alpha = 0.05, 
                  n_cl = 2, 
                  verbose = TRUE,
                  global = FALSE, 
                  pairwise = FALSE, 
                  dunnet = FALSE, 
                  trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)
```
